small_k = 0.0002   #空气阻力
big_k = 0.0008
v9 = 8.7           #弹速
v15 = 14.6
v16 = 15.6
v18 = 16.4
v30 = 27.4
l = 0.0            #枪长
theta_l = -45.0    #仰角下界
theta_r = 45.0     #仰角上界
theta_d = 0.01     #仰角步长
x_l = 0.0          #距离下界
x_r = 10.0         #距离上界
x_n = 1000          #距离步数
y_l = -5.0         #高度下界
y_r = 5.0          #高度上界
y_n = 1000          #高度步数
