[camera]
F = [[1273.5096931699643, 0.0, 281.6342455704224,],[0.0, 1274.412923337173, 356.51342207682484,],[0.0, 0.0, 1.0,],]
C = [-0.22375498735597868, 0.28173237030830756, 0.0023061024316095753, -0.002034056774360411, -2.3013327557759515,]

[bridge]
use_can = false
serial_name = "/dev/ttyUSB0"
serial_rate = 115200
send_id = 0x001
recv_id = 0x002

[sensor]
[sensor.camera]
serial_number = ""
exposure_time_mine = 200.0
exposure_time_exchangesite = 25.0
frame_rate = 60
frame_width = 1280
frame_height = 720
operator_cam_index = 0
vision_cam_index = 0

[visual]
[visual.camera]
visual_status = 1
view = 0
camp = 1

[visual.transform]
tran_tvecx = 173.0
tran_tvecy = 38.0
tran_tvecz = 40.0
bias_tevcx = 0.0
bias_tevcy = 0.0
bias_tevcz = -25.0

[calibration]
cali_x = 300.0
cali_y = 0.0
cali_z = 300.0
cali_roll = 90.0
cali_yaw = 0.0
cali_pitch = 90.0


[traditional]
[traditional.gold]
gold_thresh = 70
gold_maxval = 255

[traditional.changesite]
site_min_rate = 0.3
site_max_rate = 3.0
site_min_area = 400.0
site_max_area = 12000.0
site_area_rate = 0.7

[debug]
default_mode = 2