# Global

# Sensor
[sensor]

# Detector
[detector]

[detector.mine]
path = "models/v8/ " # path to model (without ext name)
nms_thresh = 0.7
conf_thresh = 0.60
merge_thresh = 0.8

[detector.exchangesite]
path = "models/v8/ "
nms_thresh = 0.7
conf_thresh = 0.7
merge_thresh = 0.8

# Predictor
[predictor]
constants_prefix = "config/constants/"
constants_default = "constants.default.toml"

# Log
[log]
level = "debug" # default log_level
info_prefix = "logs/Info_"
error_prefix = "logs/Error_"

[log.record]
sensor_prefix = "logs/raw"
sensor_fps = 30 # -1 for use sensor config
detector_prefix = "logs/records"
detector_fps = 15
image_prefix = "logs/image"
image_stride = 5
shot_prefix = "logs/screenshot"

# Video
[video]
image_read = false
image_log = true
image_path = "benchmark/B1.mp4"



