# Global
run_mode = "Mine" # default run mode

[predictor]
constants = "engineer.toml" # Predictor相关常数文件

# Debug
[debug]
video = "../last.mp4"

[log]

[log.record]
# 相机内录
sensor_need = true
# 含目标框内录
detector_need = true
# Image Recorder
image_need = false



[watchdog]
# 抑制看门狗reset失败的时候的重启
reboot_disabled = true